-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 15:51:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DentAid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DentAid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DentAid` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `DentAid`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`tipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(15) NULL,
  `primerApellido` VARCHAR(15) NULL,
  `segundoApellido` VARCHAR(15) NULL,
  `contrasena` VARCHAR(30) NULL,
  `estado` VARCHAR(15) NULL,
  `idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_usuario_tipexpedienteexpedienteusuariooUsuario1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `DentAid`.`tipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`telefono` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(15) NULL,
  `telefonoEmergencia` VARCHAR(15) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Telefono_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `DentAid`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`expediente` (
  `idExpediente` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(15) NULL,
  `fechaNacimiento` DATE NULL,
  `tipoSangre` VARCHAR(5) NULL,
  `residencia` VARCHAR(100) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idExpediente`),
  CONSTRAINT `fk_Expediente_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `DentAid`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `tipoEspecialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`medicoConsulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`medicoConsulta` (
  `idMedicoConsulta` INT NOT NULL AUTO_INCREMENT,
  `consultorioUbicacion` VARCHAR(60) NULL,
  `precio` DECIMAL NULL,
  `idUsuario` INT NOT NULL,
  `idEspecialidad` INT NOT NULL,
  PRIMARY KEY (`idMedicoConsulta`),
  CONSTRAINT `fk_medicoConsulta_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `DentAid`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicoConsulta_especialidad1`
    FOREIGN KEY (`idEspecialidad`)
    REFERENCES `DentAid`.`especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
	`titulo` VARCHAR(50) NULL DEFAULT NULL,
	`fechaHoraInicial` timestamp NULL DEFAULT NULL,
	`fechaHoraFinal` timestamp NULL DEFAULT NULL,

	`disponible` VARCHAR(1) ,
  `idMedicoConsulta` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  CONSTRAINT `fk_horario_medicoConsulta1`
    FOREIGN KEY (`idMedicoConsulta`)
    REFERENCES `DentAid`.`medicoConsulta` (`idMedicoConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`categoriaAlergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`categoriaAlergia` (
  `idcategoriaAlergia` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoriaAlergia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`alergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`alergia` (
  `idAlergia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NULL,
  `reaccion` VARCHAR(150) NULL,
  `observaciones` VARCHAR(150) NULL,
  `idcategoriaAlergia` INT NOT NULL,
  PRIMARY KEY (`idAlergia`),
  CONSTRAINT `fk_alergia_categoriaAlergia1`
    FOREIGN KEY (`idcategoriaAlergia`)
    REFERENCES `DentAid`.`categoriaAlergia` (`idcategoriaAlergia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`enfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`enfermedad` (
  `idEnfermedad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NULL,
  `observaciones` VARCHAR(150) NULL,
  PRIMARY KEY (`idEnfermedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`cirugia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`cirugia` (
  `idCirugia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `lugar` VARCHAR(160) NULL,
  `idExpediente` INT NOT NULL,
  PRIMARY KEY (`idCirugia`),
  CONSTRAINT `fk_cirugia_Expediente1`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `DentAid`.`expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`idMedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(15) NULL,
  `idUsuario` INT NOT NULL,
  `idHorario` INT NOT NULL,
  PRIMARY KEY (`idCita`),
  CONSTRAINT `fk_cita_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `DentAid`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_horario1`
    FOREIGN KEY (`idHorario`)
    REFERENCES `DentAid`.`horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`expedienteEnfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`expedienteEnfermedad` (
  `idExpediente` INT NOT NULL,
  `idEnfermedad` INT NOT NULL,
  PRIMARY KEY (`idExpediente`, `idEnfermedad`),
  CONSTRAINT `fk_expedienteEnfermedad_expediente1`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `DentAid`.`expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expedienteEnfermedad_enfermedad1`
    FOREIGN KEY (`idEnfermedad`)
    REFERENCES `DentAid`.`enfermedad` (`idEnfermedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`expedienteAlergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`expedienteAlergia` (
  `idExpediente` INT NOT NULL,
  `idAlergia` INT NOT NULL,
  PRIMARY KEY (`idAlergia`, `idExpediente`),
  CONSTRAINT `fk_expedienteAlergia_alergia1`
    FOREIGN KEY (`idAlergia`)
    REFERENCES `DentAid`.`alergia` (`idAlergia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expedienteAlergia_expediente1`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `DentAid`.`expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentAid`.`expedienteMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DentAid`.`expedienteMedicamento` (
  `idExpediente` INT NOT NULL,
  `idMedicamento` INT NOT NULL,
  PRIMARY KEY (`idExpediente`, `idMedicamento`),
  CONSTRAINT `fk_expedienteMedicamento_expediente1`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `DentAid`.`expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expedienteMedicamento_medicamento1`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `DentAid`.`medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `dentaid`.`espediente_compartido` (
  `idEspediente_compartido` INT NOT NULL AUTO_INCREMENT,
  `permisos` VARCHAR(45) NULL,
  `idUsuario` INT(11) NOT NULL,
  `idExpediente` INT(11) NOT NULL,
  PRIMARY KEY (`idEspediente_compartido`, `idUsuario`),
  CONSTRAINT `fk_espediente_compartido_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dentaid`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espediente_compartido_expediente1`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `dentaid`.`expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


use dentaid;
/* opcion 1 
ALTER TABLE medicoconsulta
ADD UNIQUE (idUsuario);

ALTER TABLE espediente_compartido
ADD UNIQUE (idUsuario);

ALTER TABLE espediente_compartido
ADD UNIQUE (idExpediente);
*/

/* opcion 2 */
ALTER TABLE `dentaid`.`medicoconsulta` 
ADD UNIQUE (`idMedicoConsulta`) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
